return PlaceObj('ModDef', {
	'title', "The Nests Awaken!",
	'description', '[h1] A new disaster looms![/h1]\n[h3]A crumb of new content for these thirsting for more.[/h3]\n\n[h2]The nests will now realize that you are a threat, and must be cleansed![/h2]\n\nThis mod adds:\n1. New mechanics for nests (Shrieker, Scissorhand, and a new Consortium "Nest") that "learns" about the players presence.\n1a. They now consume nearby resources slowly (Unless awoken). To do what? Create more & Evolve their defenders!\n1b. If awoken, those defenders will instead be attacking you!\n\n2. A new looming disaster where a single species attempts world domination!\nThe specific species is semi-random, and there is a semi-hidden way for you to pick the one you want.\n\n3. Four new expedition sites (One for each nest species and a special bonus one) that can be found while exploring. Each with 3 different event chains with negative and positive results! With each event having the ability to influence the nests on the game map.\n\n4. Totally unrelated (I promise) there is a new reward type from expeditions, Tamed animals! Now you can convince and bring home "friends" from afar.\n\n5. Mod settings to set how you want notifications about nearby nests.\n\nBut be warned awoken nests are [b]much[/b] harder to kill.\n\nYour difficulty choice greatly influences how to end the disaster, how fast the nests grow and send attacks, and a few other misc things.\n\n[h3]Plans:[/h3]\nI plan to develop for this mod:\n- New nest types (Shogu, Camel, etc...)\n- Species specific rewards for fending off the disaster\n- More expeditions or events that let you interact with the flora/fauna of the planet\n\n[b]This mod does heavily use and rely on Enemys Evolve mod[\\b]',
	'image', "Mod/TGkJ3Tu/Pics Or it Didn't Happen/Shrieker_Nest_small.png",
	'last_changes', "Update 1.3 Fixes, Fixes, Fixes\n\n#1 Major Change: The mechanic where each species/faction will get angry if the player consumes resources have been changed.\nConsortium -> Silicon & Synthetic Leather (Was ore and silicon)\nScissorhands -> Ore & Raw Red Meat (Was stone and red meat)\nShriekers resources are unchanged (Carbon Nanotubes and Raw Insect Meat)\nNOTE: This is done to avoid Ore & Silicon being tied to Consortium, leading to maps being overrun with clankers\n\n#2 Major Change: When a species gets angry at the player, there is now the following gates:\nA. -> The cooldown to spawning a new nest is ~1x how often attacks can occur\nB. -> Each species is now limited to a cap of 15 nests on the game map\nC. -> The cooldown for this event to evolve a nest is ~3x longer than how often attacks to occur\nD. -> If this aggression event cannot spawn or evolve, it will grant the next species attack a small buff to their next attack.\n(This attack strength is <em>ONLY</em> granted for the next attack, and reset)\n\n#3 Enemy Buff: Basic Consortium robots are no longer harvest bots, but light assault class units.\n\n#4 Bugfix: Robot Nest Units will now properly respond to player attacks with all nest units joining in.\n\n#5 Enemy Buff: Robot nest units now have a shield when near their support structures, granting them 1 day of 50% Damage Reduction once in combat.\n\n#6 Bugfix: Nest attacks are no longer always equal to the colony strength/score, but scale from 30% to 200%,\nMore nests of the same species == weaker nest attacks of that species\nEach attack a nest has done = that nest will send a slightly stronger attack\nIf an aggression event doesn't trigger an evolution or spawn of a nest,  \n\n#7 Bugfix: Resolved bug causing Nests to into a permanent attack triggering loop after a certain amount of GameTime had passed in a game.\n\n#8 QoL for me, the dev: Code grouped better so I can stay sane for longer.\n\nBugs I'm aware of:\n- Consortium Nest locations still spawn robots even after death.\n- Consortium support nest buildings cannot be interacted with\n\nAny issues with this.... very complex mod please include the logs so I can track down why.",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "rtw6tLg",
			'title', "Insects Level up All Species",
			'version_major', 4,
			'version_minor', 5,
		}),
		PlaceObj('ModDependency', {
			'id', "sad_commonlib",
			'title', "SAD_CommonLib",
			'version_major', 1,
			'version_minor', 12,
		}),
	},
	'id', "TGkJ3Tu",
	'author', "Ark Builder",
	'version_major', 1,
	'version_minor', 2,
	'version', 114,
	'lua_revision', 233360,
	'saved_with_revision', 373414,
	'entities', {
		"PXTeslaRod",
		"PXPowerFacility",
		"PXSatelite",
	},
	'code', {
		"Code/EnhancedTerritorialNest_class.lua",
		"Code/Consortium_nest_class.lua",
		"Code/Disaster_functions.lua",
		"Code/Expedition_Functions.lua",
		"Code/aggression_code.lua",
		"Code/helper_functions.lua",
		"Code/all.lua",
		"Entities/PXTeslaRod.lua",
		"Entities/PXPowerFacility.lua",
		"Entities/PXSatelite.lua",
	},
	'has_options', true,
	'has_data', true,
	'saved', 1764252006,
	'code_hash', 4227422820562639385,
	'steam_id', "3479479720",
	'TagAnimals', true,
	'TagGameplay', true,
})