return PlaceObj('ModDef', {
	'title', "The Nests Awaken!",
	'description', '[h1]The nests has observed humanity for too long.[/h1]\n[h2]Now they realize you and you alone are the greatest threat, and will react accordingly.[/h2]\n[h3]A crumb of new content for these thirsting for more.[/h3]\n\n[h2][b]This mod adds:[/b][/h2]\n1. New mechanics for nests.\n2. New nest(s)!\n3. New mechanics for Species themselves!\n4. New expeditions placing your colonists more interactions with the species of the world.\n\n[h2]1. New Nest mechanics[/h2]\nNests will now:\n- Keep track of what other species it has "met".\n-- This includes [b]humans[/b], and most species consider\n them "kill on site".\n- Slowly grow and release waves of their brood\n- Evolve their brood into their higher tiers (Thanks to Enemies Evolve)\n- Consume nearby trees/rocks/crops, speeding up the growth of their waves\n- Expand their circle of terrain if they run out of nearby resources\n\nImportant notes:\n- If a nest is aware of a hostile other group, it will speed up it\'s growth, consumption, and evolution!\n- If the nest is aware of a hostile other group, the brood releases will instead be attacks against them (You mainly)\n- Each attack a nest sends will make the next attack be stronger\n-- This [i]is[/i] capped based on game time and the # of nests of this species on the map.\n\n[h2]2. New Nests[/h2]\nWhen a map generates, it spawns either Shrieker or Scissorhand nests for the player to interact with.\nThose 2 base game nests have the above behaviors.\n\nThe [b]Consortium[/b] has released a new product line that automatically mines planets.\nThis collection of buildings produces robots, and whatever they extract from the land is used to repair/rebuild/improve it\'s efficiency.\n\n[b]I plan to slowly add more types as time passes.[/b]\nFirst up are the Dragonly and Shogu species.\n\n[h2]3. New Species mechanics[/h2]\nCertain things [b]you[/b] do will attract an unwanted kind of attention from the fauna of this world.\nThe pollution caused by smelting, the tremors that come from large construction projects, destroying/killing members of a species (or their nest).\n\nEach species has unique triggers, and generally have a higher chance to trigger based on the decisions you make.\nFor ex. A recipe that consumes 100 carbon nanotubes is more likely to cause unwanted Shrieker attention than a recipe that consumes 10 carbon nanotubes\n\nWhen you receive this attention, one of these following will occur:\n- A nest of that species will become aware of the player\n-- This means the nest will start to attack the player, and grow much faster than normal.\n- Have a new nest of a species spawn somewhere on the map\n- Trigger a nest to consume multiple nearby resource nodes\n-- Thus speeding up their growth and their next attack.\n- Keep a grudge, and the next nest to attack the player will receive a minor attack strength buff\n\n[i]Most reactions are gated by cooldowns, or have some lua code that makes sure it can/should be done.[/i]\n\n\n[b]WiP[/b]\nI plan to also add more reactions as time passes.\nI plan to add clear mechanics for the player to lower the aggression levels of specific species.\n\n[h2]4. New Expeditions[/h2]\nThere is at least 1 expedition per nest type available.\nWith each expedition within this mod having outcomes that interact with the above species mechanics!\nAnd each having the ability to bring home a low/medium/high tier unit from the expedition (Thanks to the EE and Friendly Expedition submods)\n\n[b]WiP[/b]\nI plan to expand slowly with more expeditions, and I garuntee that each new nest type will release with at least 1 expedition about it.\n\n\n[h1]Links and misc stuff![/h1]\n\nWhen you find bugs in this mod (Or if you find this mod does not live up to its goals), you are more than welcome to:\n1. Comment on the steam works\n2. Comment on the Nexus Mods item\n3. Open a Git issue at: [url=https://github.com/757Bkob/SAD_Nests]Enemies Evolve git link[/url]\n\nIf you want to translate this mod into another language, I am working to extract all my mods into this [url=https://docs.google.com/spreadsheets/d/1ETvz1lXC7nTnz8EYA3_NCHBmFeGaVeBHGVz_vkvTvOs/edit?usp=sharing]google sheet[/url].\n(And include what version it was extracted from)\n(Note EE currently is having "difficulties" exporting it\'s translation tables, so it is not there yet (tm))\n\n[i]A compatibility disclaimer[/i]\nThis mod requries both my [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3350915173]Enemies Evolve[/url] & [url=https://steamcommunity.com/sharedfiles/filedetails/?id=3643615905]Friendly Expeditions[/url] mod to work.',
	'image', "Mod/TGkJ3Tu/PicsOritDidntHappen/Preview.png",
	'last_changes', 'Update 2 Major Update Hotfix #4\n \nHotfix #4.1 Corrected code around Consortium nest upgrades\n\nHotfix #4.2 Corrected code around Consortium nest attacks\n\nHotfix #4.3 Corrected code around passive spawning of units, which still had the "spawn directly underneath nest" bug\n\nHotfix #3.1 Removed temp function that no longer exists in the nest attack spawndef\n\nHotfix #2.1 Nests now attacks with ~1/3 of their attack strength as their strongest unit, ~1/2 of their strength in their middle tier unit, and ~1/6 of their strength in their weakest units\n\nHotfix #2.2 Updated code checking if the nest should evolve it\'s units to align with the above\n\nHotfix #2.3 Bugfix Corrected code causing nests to only attack with a single unit.\n\nHotfix #2.4 Overrode all notifications around attacks to not override the sound, due to how often Nests will be attacking with this mod loaded.\n\nHotfix #1.1 Corrected bug in code causing units with nest attack move speed to cause an error when trying to remove a stack of the speed boost\n\nHotfix #1.2 Deleted all storybits about the disaster to avoid triggering.\n(This includes a savegame cleanup to disable active solar eclipses)\n\n#1 Major change: Nests are now handled at a game class level, and support basic functions.\n\n#2 Nests use EE\'s evolution chains to evolve\n\n#3 Aggression up/down events can now be added as mod UI items\n\nAny issues with this.... very complex mod please include the logs so I can track down why.\nAlso any thoughts on what species should do when angered/pacified are welcome!\nLooking to expand the # of things nests/species do to be quite varied to bring more fun to your games.',
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "rtw6tLg",
			'title', "Insects Level up All Species",
			'version_major', 4,
			'version_minor', 5,
		}),
		PlaceObj('ModDependency', {
			'id', "sad_commonlib",
			'title', "SAD_CommonLib",
			'version_major', 1,
			'version_minor', 12,
		}),
		PlaceObj('ModDependency', {
			'id', "Uqo4QkN",
			'title', "Expeditions can find friends!",
			'version_major', 1,
		}),
	},
	'id', "TGkJ3Tu",
	'author', "Ark Builder",
	'version_major', 2,
	'version', 157,
	'lua_revision', 233360,
	'saved_with_revision', 373414,
	'entities', {
		"PXTeslaRod",
		"PXPowerFacility",
		"PXSatelite",
	},
	'code', {
		"Code/EnhancedTerritorialNest_class.lua",
		"Code/Consortium_nest_class.lua",
		"Code/Disaster_functions.lua",
		"Code/Nest_Expedition_Functions.lua",
		"Code/aggression_code.lua",
		"Code/NestingSpeciesPreset.lua",
		"Code/helper_functions.lua",
		"Entities/PXTeslaRod.lua",
		"Entities/PXPowerFacility.lua",
		"Entities/PXSatelite.lua",
	},
	'has_options', true,
	'has_data', true,
	'saved', 1769276650,
	'code_hash', -2711785383735530044,
	'steam_id', "3479479720",
	'TagAnimals', true,
	'TagGameplay', true,
})